
version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdatabase
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432" # Ensure this port is not used by your local Postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
